"""remove goal from habits

Revision ID: ccaaf92a22c1
Revises: b69852a28e19
Create Date: 2026-10-09 14:43:55.740640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccaaf92a22c1'
down_revision: Union[str, Sequence[str], None] = 'b69852a28e19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habits', 'goal')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('goal', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
